### ISSUE TITLE
[WIP] Roadmap

### ISSUE THREAD

**Issue by muziejus** [wandertext/wandertext#160]
v 0.6.0 — Apollo
- [x] Make it look good. #213
- [x] Move adapter from Emberfire to Apollo #287

v 0.7.0 — minimum public demo
- [ ] Implement entry creation #316
- [ ] A text's entries column can be visualized. #172
- [ ] Use all glimmer components. #286
- [ ] Viewer views Texts (#28), Text (#41), Places (#29), Place (#33)
- [x] There is a substantial About #5)
- [ ] Carousel on opening page #37)
- [ ] Viewer can select a place in a text #43)
- [ ] Viewer can leave a Flag #34)
- [ ] Appropriate CUL branding #36)
- [ ] Histogram of Entries in a Text #42)
- [ ] Histogram of a selected Place in a Text #44)

v 0.9.0 — public demo with API read access
- [ ] Text data can be exported

v 1.0 — public site accepting new data
- [ ] Allow contributor to create entry #26 

Future functionality:
- [ ] Viewer can search for places  (#50)
