### ISSUE TITLE
Build <Menu> component

### ISSUE THREAD

**Issue by muziejus** [wandertext/wandertext#709]
The Menu component appears on every page of the application, typically accessed by a button in the header or by a FAB if the typical header is missing.

- [ ] Menu should display Wandertext name and logo in a way similar to the generic app header.
- [X] Menu should be made up of Menu::Items that create a list of buttons the user can use.
- [ ] Menu should have a footer with Columbia-related copyright information.
- [ ]  Menu should slide in from the right when the menu icon is activated.
- [ ] Menu should slide in from the right with a two-fingered swipe.
