### ISSUE TITLE
Build <Menu::Item/> component

### ISSUE THREAD

**Issue by muziejus** [wandertext/wandertext#715]
The `<Menu::Item/>` component:

- [x] shows the active state of the current route
- [x] Is styled appropriately, where "active" is indicated by a Columbia blue background
- [ ] lights up on hover
- [X] acts as a link to a route (c1705c6e9595aea79e8f34c003304907c491bd82).
